/**
 * How a receipt is identified.
 *
 * Two codes, because a receipt is asked for in two completely different
 * situations and one string cannot serve both:
 *
 * - `code` — "REC-2026-00042". Sequential, predictable, human. This is the
 *   accountant's handle and the number written in a ledger book. It has to be
 *   gapless and it has to be guessable, because "give me receipt 42" is a thing
 *   people say.
 *
 * - `lookupCode` — "K7M2-9XQR". Random, unguessable, short enough to read down
 *   a phone. This is what goes in a link sent over WhatsApp. It exists BECAUSE
 *   `code` is predictable: a sequential number in a URL means anybody holding
 *   one receipt can walk the numbers and read every other customer's.
 *
 * Confusing the two is a real and quiet privacy failure, which is why they are
 * generated by two different functions with two different alphabets in one file
 * that says so.
 */

import { randomInt } from "node:crypto";

/* -------------------------------------------------------------------------- */
/* The sequence                                                                */
/* -------------------------------------------------------------------------- */

/** How the sequence is written for people. */
export function formatReceiptCode(year: number, sequence: number): string {
  return `REC-${year}-${String(sequence).padStart(5, "0")}`;
}

/**
 * The next number in the sequence, given the highest one already issued.
 *
 * Deliberately takes the maximum rather than a count. A count repeats a number
 * the first time a receipt is voided, and a duplicated receipt number is the
 * single most damaging thing that can happen to a book of receipts: two
 * different documents, both claiming to be REC-2026-00042, and no way to say
 * which one the customer was given.
 *
 * The caller must read that maximum inside the same transaction that writes the
 * new row — see routes/receipts.ts. `receipts_number_unique` is the backstop if
 * that is ever got wrong.
 */
export function nextReceiptNumber(highestIssued: number | null | undefined): number {
  return (highestIssued ?? 0) + 1;
}

/* -------------------------------------------------------------------------- */
/* The lookup code                                                             */
/* -------------------------------------------------------------------------- */

/**
 * Crockford's base32, which drops I, L, O and U.
 *
 * I/1, O/0 and the rest are the characters people transpose when reading a code
 * off a screen and typing it into a phone, and U is left out so the alphabet
 * cannot spell anything unfortunate. 32 characters over 8 places is 2^40
 * possibilities — far too many to walk, and still short enough to say out loud.
 */
const LOOKUP_ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";

const LOOKUP_LENGTH = 8;

/**
 * A fresh, unguessable lookup code, written "K7M2-9XQR".
 *
 * `randomInt` rather than `Math.random`: this value is a capability — anyone
 * holding it can read the receipt — and `Math.random` is a predictable PRNG
 * that must never be used to mint one. The hyphen is display only and is
 * stripped by `normalizeLookupCode` before anything is compared.
 */
export function generateLookupCode(): string {
  let code = "";

  for (let index = 0; index < LOOKUP_LENGTH; index += 1) {
    code += LOOKUP_ALPHABET[randomInt(LOOKUP_ALPHABET.length)];
  }

  return `${code.slice(0, 4)}-${code.slice(4)}`;
}

/**
 * The comparable form of a lookup code somebody typed in.
 *
 * Uppercased, punctuation dropped, and the four characters Crockford excludes
 * folded onto the ones they are mistaken for — so a customer who reads "0" as
 * "O" off a printed receipt still finds their document instead of being told it
 * does not exist.
 */
export function normalizeLookupCode(raw: string): string {
  return raw
    .toUpperCase()
    .replace(/[^0-9A-Z]/g, "")
    .replace(/[IL]/g, "1")
    .replace(/O/g, "0")
    .replace(/U/g, "V");
}

/**
 * A typed lookup code in the exact form the column stores.
 *
 * The database holds the display form with its hyphen ("K7M2-9XQR"), so the
 * comparison has to happen on one agreed shape rather than by hoping the user
 * typed the punctuation. Anything that is not eight characters after
 * normalising is not a lookup code at all, and says so by returning null rather
 * than by running a query that cannot match.
 */
export function toStoredLookupCode(raw: string): string | null {
  const normalized = normalizeLookupCode(raw);

  if (normalized.length !== LOOKUP_LENGTH) {
    return null;
  }

  return `${normalized.slice(0, 4)}-${normalized.slice(4)}`;
}
