import { sql } from "drizzle-orm";
import { integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

/**
 * Lindero's database schema.
 *
 * Conventions, applied everywhere:
 *
 * - IDs are text UUIDs, not auto-increment integers. They are generated by the
 *   application, so a record can be referenced before it is written, and they
 *   move to PostgreSQL unchanged.
 * - Money is an INTEGER number of centavos. Never a float. Column names end in
 *   `Cents` so the unit is impossible to forget at a call site.
 * - Timestamps are ISO-8601 text ("2026-08-26T00:38:08.055Z"). SQLite has no
 *   date type; ISO text sorts correctly, is readable when you open the file,
 *   and converts cleanly to a PostgreSQL `timestamptz` later.
 * - Nothing financial is ever deleted. Rows are archived or reversed.
 */

const timestamp = (name: string) => text(name).notNull().default(sql`CURRENT_TIMESTAMP`);

/* -------------------------------------------------------------------------- */
/* Identity                                                                    */
/* -------------------------------------------------------------------------- */

export const users = sqliteTable(
  "users",
  {
    id: text("id").primaryKey(),
    email: text("email").notNull(),
    name: text("name").notNull(),
    /** "owner" or "staff" — see src/lib/permissions.ts */
    role: text("role").notNull(),
    /** scrypt hash. The plain password is never stored or logged. */
    passwordHash: text("password_hash").notNull(),
    createdAt: timestamp("created_at"),
  },
  (table) => [uniqueIndex("users_email_unique").on(table.email)],
);

/**
 * Server-side sessions.
 *
 * The browser only ever holds the session id, in an HTTP-only cookie it cannot
 * read from JavaScript. Everything that matters — who you are, what role you
 * have — is looked up here, server-side, on every request. That is why a user
 * editing their own cookie cannot promote themselves.
 */
export const sessions = sqliteTable("sessions", {
  id: text("id").primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => users.id),
  expiresAt: text("expires_at").notNull(),
  createdAt: timestamp("created_at"),
});

/**
 * What each ROLE is allowed to do, as edited by the supervisor.
 *
 * One row per switch, carrying an explicit `enabled`, rather than "a row means
 * granted". The difference matters: a supervisor who turns EVERY permission off
 * must not be indistinguishable from a database nobody has configured, or
 * revoking everything would silently restore the defaults — which is the
 * opposite of what was asked for. Rows present means configured; no rows at all
 * means fall back to the defaults in src/lib/permissions.ts.
 *
 * Only `staff` is ever stored. The owner's capabilities are not editable and
 * are not read from this table: a supervisor who could revoke their own
 * `user:manage` would lock everyone out of the only account that can undo it.
 */
export const roleCapabilities = sqliteTable(
  "role_capabilities",
  {
    role: text("role").notNull(),
    capability: text("capability").notNull(),
    enabled: integer("enabled", { mode: "boolean" }).notNull(),
    /** Who set it, and when — the same question the audit log answers. */
    grantedBy: text("granted_by").references(() => users.id),
    grantedAt: timestamp("granted_at"),
  },
  (table) => [uniqueIndex("role_capabilities_unique").on(table.role, table.capability)],
);

/**
 * The lempira-per-dollar rate, as a HISTORY rather than a single value.
 *
 * Append-only, like payments: a new reading is a new row, never an overwrite.
 * That way "what did we think a dollar was worth on 12 August" always has an
 * answer, which matters the first time somebody queries a figure on an old
 * screenshot.
 *
 * This rate is DISPLAY ONLY. It converts figures on screen so a buyer can be
 * told roughly what a lot costs in dollars. It is never used to compute a
 * balance: each payment stores the rate it was actually settled at, in
 * `payments.exchange_rate`, and that is the number the accounts are built from.
 */
export const exchangeRates = sqliteTable("exchange_rates", {
  id: text("id").primaryKey(),
  /**
   * Lempiras per one US dollar, stored as TEXT to keep the provider's exact
   * decimal. A float would quietly round 26.822577 and there is no reason to
   * accept that when the value is only ever displayed and compared.
   */
  rate: text("rate").notNull(),
  /** "auto" — fetched from the provider — or "manual", typed by a supervisor. */
  source: text("source").notNull(),
  /** Named for the record, so a rate can be traced back to where it came from. */
  provider: text("provider"),
  /** Null for automatic readings: nobody typed them. */
  setBy: text("set_by").references(() => users.id),
  capturedAt: timestamp("captured_at"),
});

/* -------------------------------------------------------------------------- */
/* Inventory                                                                   */
/* -------------------------------------------------------------------------- */

export const projects = sqliteTable(
  "projects",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    /**
     * The unit this project's areas are ENTERED AND SHOWN in — see
     * src/lib/area.ts for the list and the factors.
     *
     * Areas are always STORED in square metres, in `lots.area_m2`. Land here is
     * sold by the manzana or the vara cuadrada as often as by the metre, so the
     * unit is a property of the project rather than of each lot: one project is
     * sold in one unit, and keeping a single canonical stored unit means two
     * lots can always be compared, priced and totalled without asking which
     * unit each one is in.
     */
    areaUnit: text("area_unit").notNull().default("m2"),
    /**
     * Set when the project is archived. Projects are never deleted: a project
     * owns lots, which own contracts, which own payments. Deleting one would
     * cut the financial history loose from the place it happened.
     */
    archivedAt: text("archived_at"),
    archiveReason: text("archive_reason"),
    createdAt: timestamp("created_at"),
    /**
     * Nullable, unlike `lots.updated_at`, and set by the application on every
     * write rather than by a column default.
     *
     * SQLite cannot ADD a NOT NULL column whose default is CURRENT_TIMESTAMP to
     * a table that already holds rows — the default is not a constant, so there
     * is nothing to write into the existing rows. Tightening it afterwards
     * would mean rebuilding the table, and `lots` has a foreign key into this
     * one. A nullable column plus a backfill in the migration is the honest
     * trade: rows written before this column existed say `NULL`, which is true,
     * instead of claiming a modification time that was never recorded.
     */
    updatedAt: text("updated_at"),
  },
  (table) => [uniqueIndex("projects_name_unique").on(table.name)],
);

export const lots = sqliteTable(
  "lots",
  {
    id: text("id").primaryKey(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id),
    /** Lot number within its project, e.g. "A-07". */
    code: text("code").notNull(),
    areaM2: real("area_m2").notNull(),
    basePriceCents: integer("base_price_cents").notNull(),
    /**
     * Set when the lot is archived. Archiving hides it from the working
     * inventory; the row and its history stay readable forever.
     */
    archivedAt: text("archived_at"),
    archiveReason: text("archive_reason"),
    createdAt: timestamp("created_at"),
    updatedAt: timestamp("updated_at"),
  },
  // The same lot number may exist in two different projects, but not twice in
  // the same one.
  (table) => [uniqueIndex("lots_project_code_unique").on(table.projectId, table.code)],
);

/* -------------------------------------------------------------------------- */
/* People                                                                      */
/* -------------------------------------------------------------------------- */

export const customers = sqliteTable(
  "customers",
  {
    id: text("id").primaryKey(),
    fullName: text("full_name").notNull(),
    /** Número de identidad. */
    identification: text("identification").notNull(),
    /**
     * E.164, e.g. "+50499824471" — see src/lib/phone.ts.
     *
     * Stored with its country code and no punctuation because this is the
     * address a WhatsApp receipt will be sent to, and WhatsApp cannot dial
     * "9982-4471". The interface still shows and accepts the local form.
     */
    phone: text("phone").notNull(),
    email: text("email"),
    address: text("address"),
    customerSince: integer("customer_since").notNull(),
    /**
     * Free text about this person: how they pay, who to call instead, what was
     * agreed verbally. Deliberately unstructured — it is the column that stops
     * people keeping a second list in WhatsApp because the app had nowhere to
     * put what they know.
     */
    notes: text("notes"),
    createdAt: timestamp("created_at"),
    /**
     * Nullable and written by the application, for the same reason as
     * `projects.updated_at`: SQLite cannot add a NOT NULL column defaulting to
     * CURRENT_TIMESTAMP to a table that already holds rows. Customers written
     * before this column existed say NULL, which is true, rather than claiming
     * a modification time nobody recorded.
     */
    updatedAt: text("updated_at"),
  },
  // One person, one identity number. This is what stops the same customer being
  // entered twice and their contracts splitting across two records.
  (table) => [uniqueIndex("customers_identification_unique").on(table.identification)],
);

/* -------------------------------------------------------------------------- */
/* Contracts                                                                   */
/* -------------------------------------------------------------------------- */

/**
 * A contract joins one customer to ONE lot.
 *
 * That grain is deliberate even though a customer usually buys several lots at
 * once and thinks of it as a single purchase. Lots are released, titled,
 * cancelled and repossessed one at a time, so each one needs a balance of its
 * own: paying off two of three lots has to leave two lots transferable and one
 * outstanding, which a merged row cannot express.
 *
 * The "one purchase" the customer experiences is `saleGroupId`, and the single
 * receipt they get for it is a payment split across the group's contracts —
 * see src/lib/allocation.ts.
 *
 * Three separate concepts, none of which is allowed to stand in for another:
 *
 * - `kind`   — a temporary hold vs a signed sale.
 * - `status` — the contract's own lifecycle.
 * - payment health (al día / atrasado / en riesgo) — computed from the terms
 *   below and the posted payments, in src/lib/contracts.ts. Deliberately NOT a
 *   column: a stored alert status is stale the morning after it is written.
 *
 * Everything about how much is owed is likewise derived, never stored:
 * `financed` is salePrice − downPayment, and the balance is salePrice minus
 * the non-reversed payments. There is no balance column anywhere in Lindero.
 */
export const contracts = sqliteTable(
  "contracts",
  {
    id: text("id").primaryKey(),
    /** Human-facing number, e.g. "CT-2026-014". Assigned by the server. */
    code: text("code").notNull(),
    lotId: text("lot_id")
      .notNull()
      .references(() => lots.id),
    customerId: text("customer_id")
      .notNull()
      .references(() => customers.id),
    /**
     * The purchase this contract belongs to, or null when the lot was bought on
     * its own.
     *
     * Lots bought together are one legal document and one payment: the customer
     * hands over a single amount and gets a single receipt, which is then split
     * across the group. Grouping implicitly by customer instead would be wrong
     * for the common case of somebody who bought two lots in 2024 and a third
     * this year — a payment for the new lot must not be spread over the old
     * ones. So the group is recorded rather than guessed at.
     *
     * A plain shared id, with no table of its own. A group is always one
     * customer's, it carries nothing a contract does not already know, and it
     * cannot exist before the contracts that define it.
     */
    saleGroupId: text("sale_group_id"),
    /** "reservation" | "contract" */
    kind: text("kind").notNull(),
    /**
     * How the lot is being paid for: "financed" | "cash" | "donation".
     *
     * The Crédito / Comprado / Donación distinction, and it decides which of
     * the terms below apply at all. A financed sale has a term, a monthly
     * amount and a due day; a cash sale is settled at signing and has none of
     * them; a donation is a transfer of land for no money, recorded at a sale
     * price of zero so the lot's history says what became of it instead of the
     * lot simply going quiet.
     */
    saleType: text("sale_type").notNull().default("financed"),
    /** "draft" | "active" | "paid_off" | "cancelled" | "defaulted" */
    status: text("status").notNull().default("active"),
    /**
     * The agreed price for THIS sale, which is independent of the lot's current
     * base price. Changing a lot's list price must never alter what a customer
     * already owes.
     *
     * Always lempira centavos. A payment made in dollars keeps its own dollar
     * amount and the rate it was actually settled at, in `payments`, so the
     * bank's real rate on the day is what enters the accounts — never today's
     * display rate applied after the fact.
     */
    salePriceCents: integer("sale_price_cents").notNull(),
    /**
     * The prima as AGREED, which is not the same question as whether it has
     * been paid. Whether it arrived is summed from the payments of type
     * `down_payment`; keeping one column for both is how a spreadsheet ends up
     * insisting on a prima nobody ever handed over.
     */
    downPaymentCents: integer("down_payment_cents").notNull().default(0),
    /** How many installments were agreed. Null for a cash sale or a donation. */
    termMonths: integer("term_months"),
    /**
     * The agreed installment, stored rather than computed.
     *
     * It is tempting to derive it as financed ÷ months, but the real figure is
     * negotiated and rounded: L 47,000 over 13 months is L 3,615.38, which
     * nobody pays. A round number is agreed and the last installment absorbs
     * the difference. Computing it would quietly overwrite what was signed.
     */
    monthlyPaymentCents: integer("monthly_payment_cents"),
    /** Day of the month the installment falls due, 1–31. See src/lib/contracts.ts. */
    dueDay: integer("due_day"),
    /**
     * The date the contract was signed — the date the schedule counts from.
     * Distinct from `created_at`, which is when the row was typed in, often
     * days or years later.
     */
    signedOn: text("signed_on"),
    /**
     * When the first installment falls due, if it was negotiated rather than
     * following from the signing date. Usually null: see `firstDueDate` in
     * src/lib/contracts.ts for what is used instead.
     */
    firstDueOn: text("first_due_on"),
    /**
     * When a reservation lapses. Only meaningful for `kind = "reservation"`: a
     * hold with no expiry keeps a lot off the market forever and nobody ever
     * notices.
     */
    expiresOn: text("expires_on"),
    /**
     * When and why the contract stopped being active.
     *
     * The audit log records who did it, but the date belongs on the row: a
     * status of "cancelled" with no date cannot answer when the lot came back,
     * which is the first thing asked of a cancelled sale.
     */
    closedAt: text("closed_at"),
    closedReason: text("closed_reason"),
    /** What was agreed verbally, and anything the columns above cannot hold. */
    notes: text("notes"),
    createdAt: timestamp("created_at"),
    /**
     * Nullable and written by the application, for the same reason as
     * `projects.updated_at`: SQLite cannot add a NOT NULL column defaulting to
     * CURRENT_TIMESTAMP to a table that already holds rows.
     */
    updatedAt: text("updated_at"),
  },
  (table) => [uniqueIndex("contracts_code_unique").on(table.code)],
);

/**
 * Posted payments.
 *
 * A contract's paid-to-date is SUM(amount_cents) over its non-reversed
 * payments — computed, never stored on the contract. A mistake is corrected by
 * writing a reversal, not by editing or deleting the original row.
 */
export const payments = sqliteTable("payments", {
  id: text("id").primaryKey(),
  contractId: text("contract_id")
    .notNull()
    .references(() => contracts.id),
  /** Amount in the CONTRACT's currency, in centavos. This is what counts. */
  amountCents: integer("amount_cents").notNull(),
  /** What the customer actually handed over, before conversion. */
  originalAmountCents: integer("original_amount_cents").notNull(),
  originalCurrency: text("original_currency").notNull(),
  /**
   * Rate used for this specific payment, stored as text to keep full decimal
   * precision. Balances are never recomputed from today's rate.
   */
  exchangeRate: text("exchange_rate").notNull(),
  /** Calendar date of the payment (YYYY-MM-DD), not the row's insert time. */
  paidOn: text("paid_on").notNull(),
  /** "cash" | "transfer" | "card" */
  method: text("method").notNull(),
  /** "down_payment" | "installment" | "full_payment" | "adjustment" | "reversal" */
  type: text("type").notNull(),
  recordedBy: text("recorded_by")
    .notNull()
    .references(() => users.id),
  reversedAt: text("reversed_at"),
  createdAt: timestamp("created_at"),
});

/* -------------------------------------------------------------------------- */
/* Audit                                                                       */
/* -------------------------------------------------------------------------- */

/**
 * Append-only history of who changed what.
 *
 * Written for every role including the owner. `reason` is only populated for
 * the few actions that demand a justification (archiving, cancelling,
 * reversing, repricing) — asking on every edit trains people to type "x".
 */
export const auditEvents = sqliteTable("audit_events", {
  id: text("id").primaryKey(),
  actorId: text("actor_id")
    .notNull()
    .references(() => users.id),
  /** "lot" | "project" | "customer" | "contract" | "payment" | "user" | "role" | "exchange_rate" */
  entityType: text("entity_type").notNull(),
  entityId: text("entity_id").notNull(),
  /** "create" | "update" | "archive" | "cancel" | "reverse" | "login" */
  action: text("action").notNull(),
  reason: text("reason"),
  /** JSON snapshots of the changed fields, so a diff can be shown later. */
  beforeJson: text("before_json"),
  afterJson: text("after_json"),
  createdAt: timestamp("created_at"),
});
